- name: Installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Start and enable the nginx service 
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true


- name: include from common role 
  ansible.builtin.include_role:
    name: common
    tasks_from: main

- name: copy expense config
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - Restart nginx service
